language: php
php:
  - 5.4
  - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - cp src/Resources/config/default-settings.yml src/Resources/config/settings.yml


script: phpunit