debug: true

base_url: http://www.local.dev/Silex-Skeleton/

default_language: nl
languages: [nl, fr, en]

google_analytics:
    code: UA-XXXXXXX-1
    id: XXX #Last numbers of job nr
    name: Yunomi #used in GA tracking!

database:
    driver: pdo_mysql
    host: localhost
    dbname: test
    user: user
    password: password

facebook:
	app_id: xxxxx #This is needed for share macro
    secret: xxxxx #This is needed for an interactive app

#This will enable/dissable all tab features (mobile redirect, facebook auto size, ...)
facebook_activate_tab: true