debug: true

base_url: http://www.local.dev/Silex-Skeleton/

default_language: nl
languages: [nl, fr, en]

google_analytics:
    code: UA-XXXXXXX-1
    id: XXX #Last numbers of job nr
    name: Yunomi #used in GA tracking!

database:
    driver: pdo_mysql
    host: localhost
    dbname: test
    user: user
    password: password

#Basic information needed for facebook
facebook:
    app_id: 784634591576735
    secret: ba560a668f4634038119962fbf12bddb
    tab: https://www.facebook.com/headoffice.envee/app_784634591576735 #tab url if you want redirect action to work
    start_route: index #The route you will be redirected to if mobile or if liked