# routes.yml
start:
    pattern:   /
    defaults:  { _controller: 'Controller\RedirectController::redirectAction', path: index, slugs: {_locale: nl} }

start_fr:
    pattern:   /fr
    defaults:  { _controller: 'Controller\RedirectController::redirectAction', path: index, slugs: {_locale: fr} }

index:
  path: /{_locale}/index
  defaults: { _controller: 'Controller\ApplicationController::indexAction' }

step1:
  path: /{_locale}/step1
  defaults: { _controller: 'Controller\ApplicationController::step1Action' }


#Facebook Routing
facebook_fangate:
  path: /fangate
  defaults: { _controller: 'Controller\FacebookController::fangateAction' }

facebook_redirect:
  path: /fbredirect
  defaults: { _controller: 'Controller\FacebookController::redirectAction' }