# routes.yml
start:
    pattern:   /
    defaults:  { _controller: 'Controller\RedirectController::redirectAction', path: home, slugs: {_locale: nl} }

start_fr:
    pattern:   /fr
    defaults:  { _controller: 'Controller\RedirectController::redirectAction', path: home, slugs: {_locale: fr} }

home:
  path: /{_locale}/home
  defaults: { _controller: 'Controller\HomeController::indexAction' }