debug: true

base_url: http://www.example.com

default_language: nl
languages: [nl, fr, en]

google_analytics: UA-XXXXX-X


database:
    driver: pdo_mysql
    host: localhost
    dbname: dbname
    user: user
    password: password
