debug: true

base_url: http://www.local.dev/Silex-Skeleton/

default_language: nl
languages: [nl, fr, en]

google_analytics:
    code: UA-XXXXXXX-1
    id: XXX #Last numbers of job nr
    name: Yunomi #used in GA tracking!

facebook_id: xxxxx


database:
    driver: pdo_mysql
    host: localhost
    dbname: skeleton_test
    user: user
    password: password
