debug: true

base_url: http://test.pix-art.be:42013/

default_language: nl
languages: [nl, fr, en]

google_analytics:
    code: UA-32893269-1
    id: XXX #Last numbers of job nr
    name: Yunomi #used in GA tracking!

facebook_id: xxxxx


database:
    driver: pdo_mysql
    host: localhost
    dbname: dbname
    user: user
    password: password
